"""add conversation title

Revision ID: f4667c3b0b7b
Revises: d4963368333b
Create Date: 2026-08-06 10:48:06.518744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4667c3b0b7b'
down_revision: Union[str, Sequence[str], None] = 'd4963368333b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
